export default [
   {
      "id": 1,
      "title": "My Lovely Wife",
      "author": "Rick Riordan",
      "category": "Thriller",
      "rating": 4,
      "pages": 359,
      "description": "Dexter meets Mr. and Mrs. Smith in this wildly compulsive debut thriller about a couple whose fifteen-year marriage has finally gotten too interesting",
      "cover": "https://images.gr-assets.com/books/1530546018l/39796904.jpg"

   },
   {
      "id": 2,
      "title": "Lock Every Door",
      "author": "Rick Riordan",
      "category": "Mystery",
      "rating": 4,
      "pages": 384,
      "description": "No visitors. No nights spent away from the apartment. No disturbing the other residents, all of whom are rich or famous or both. These are the only rules for Jules Larsen's new job as an apartment sitter at the Bartholomew",
      "cover": "https://images.gr-assets.com/books/1540938359l/41837243.jpg"
   },
   {
      "id": 3,
      "title": "The Night Tiger",
      "author": "Rick Riordan",
      "category": "Fiction",
      "rating": 4,
      "pages": 384,
      "description": "A sweeping historical novel about a dancehall girl and an orphan boy whose fates entangle over an old Chinese superstition about men who turn into tigers.",
      "cover": "https://images.gr-assets.com/books/1534907959l/39863482.jpg",
   },
   {
      "id": 4,
      "title": "The One",
      "author": "Stephen King",
      "category": "Romance",
      "rating": 4,
      "pages": 323,
      "description": "The time has come for one winner to be crowned.",
      "cover": "https://images.gr-assets.com/books/1395612906l/18635016.jpg",
   },
   {
      "id": 5,
      "title": "The Heir",
      "author": "Rick Riordan",
      "category": "Fantasy",
      "rating": 4,
      "pages": 342,
      "description": "Princess Eadlyn has grown up hearing endless stories about how her mother and father met. Twenty years ago, America Singer entered the Selection and won the heart of Prince Maxon",
      "cover": "https://images.gr-assets.com/books/1422993526l/22918050.jpg",
   },
   {
      "id": 6,
      "title": "The Last Time I Lied",
      "author": "Cassandra Clare",
      "category": "Mystery",
      "rating": 3,
      "pages": 384,
      "description": "Two Truths and a Lie. The girls played it all the time in their tiny cabin at Camp Nightingale. Vivian, Natalie",
      "cover": "https://images.gr-assets.com/books/1511141004l/36626748.jpg",
   },
   {
      "id": 7,
      "title": "The Ghost Bride",
      "author": "Cassandra Clare",
      "category": "Fantasy",
      "rating": 3,
      "pages": 368,
      "description": "One evening, my father asked me if I would like to become a ghost bride",
      "cover": "https://images.gr-assets.com/books/1356671808l/16248223.jpg",
   },
   {
      "id": 8,
      "title": "The River of No Return",
      "author": "Neil Gaiman",
      "category": "Romance",
      "rating": 3,
      "pages": 464,
      "description": "Two hundred years after he was about to die on a Napoleonic battlefield, Lord Nicholas Falcott wakes up in twenty-first-century London",
      "cover": "https://images.gr-assets.com/books/1379898686l/18114292.jpg",
   },
   {
      "id": 9,
      "title": "The Beautiful Land",
      "author": "Neil Gaiman",
      "category": "Science Fiction",
      "rating": 3,
      "pages": 362,
      "description": "working for the Axon Corporation as an explorer of parallel timelines—as many and as varied as anyone could imagine. A great gig",
      "cover": "https://images.gr-assets.com/books/1359984423l/15812169.jpg",
   },
   {
      "id": 10,
      "title": "Heart of Briar",
      "author": "Neil Gaiman",
      "category": "Fiction",
      "rating": 3,
      "pages": 394,
      "description": "He has been taken. And you are his only chance.",
      "cover": "https://images.gr-assets.com/books/1368431376l/17251424.jpg",
   },
]